modules/redos-core/shared/src/main/scala/codes/quine/labo/redos/automaton/EpsNFA.scala
modules/redos-core/shared/src/main/scala/codes/quine/labo/redos/automaton/EpsNFACompiler.scala
modules/redos-core/shared/src/test/scala/codes/quine/labo/redos/automaton/AutomatonCheckerSuite.scala
modules/redos-core/shared/src/test/scala/codes/quine/labo/redos/automaton/EpsNFACompilerSuite.scala
modules/redos-core/shared/src/test/scala/codes/quine/labo/redos/automaton/EpsNFASuite.scala

This PR adds two kinds of ε-transitions named `LoopEnter` and `LoopExit` to detect ε-loop on NFA construction.
Now, `r*` is compiled to the following ε-NFA:

fix(redos-core): avoid ε-loop on NFA construction correctly

---

modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFA.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFACompiler.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/data/IChar.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/data/ICharSet.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/data/unicode/IntervalSet.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/regexp/Pattern.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/automaton/AutomatonCheckerSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/automaton/EpsNFACompilerSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/automaton/EpsNFASuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/data/ICharSetSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/data/ICharSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/regexp/PatternSuite.scala

Reverts MakeNowJust-Labo/recheck#62
Because this causes serious performance down on automaton based analysis, and sometimes it is buggy.

Revert "Remove `isLineTerminator` and `isWord` flag from `IChar`"

---

CHANGELOG.md
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFA.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFACompiler.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/data/IChar.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/data/ICharSet.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzChecker.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/fuzz/Seeder.scala
modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/regexp/Pattern.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/automaton/AutomatonCheckerSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/automaton/EpsNFACompilerSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/automaton/EpsNFASuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/data/ICharSetSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/data/ICharSuite.scala
modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/regexp/PatternSuite.scala

They are moved to `ICharSet` because `IChar` is used in many places other than the `automaton` package.
These PR benefits are:
- simplified some implementations
- performance improvements (because `IChar` needs less memory space now?)

Remove `isLineTerminator` and `isWord` flags from `IChar`

---

.github/workflows/main.yml
.yarnrc

To develop NPM package, we need to add `--ignore-platform` option to `yarn` command.
It is shameful and hard to maintain workflows. Thus, we want to use `.yarnrc` to set the option.
- Add `.yarnrc` to set `--ignore-platform` option

Add `.yarnrc` to set `--ignore-platform` option

---

packages/eslint-plugin-redos/package.json

`homepage` and `repository` fields are missing in `package.json` of `eslint-plugin-redos`.
- Fill in `homepage` and `repository` of `package.json`

Fill in `homepage` and `repository` of `package.json`

---

.gitignore
site/layouts/partials/header.html

Hugo 0.89.4 uses the old esbuild, and it has a bug related to minification with bare unicode escape identifier.
For now, it fixes to not minify worker.js.
- Remove `minify` filter for `worker.js`.

Don't minify worker.js

---

.github/workflows/main.yml

- Set up Node.js on `scala-test` job because `node` is used in Scala.js testing.

Set up Node.js on scala-test

---

.sbtopts
CHANGELOG.md
build.sbt
modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/Main.scala
modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/arguments.scala
modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/ArgumentsSuite.scala
modules/recheck-codec/shared/src/main/scala/codes/quine/labo/recheck/codec/package.scala
modules/recheck-codec/shared/src/test/scala/codes/quine/labo/recheck/codec/CodecSuite.scala
modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Parameters.scala
modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Seeder.scala
modules/recheck-common/shared/src/test/scala/codes/quine/labo/recheck/common/SeederSuite.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/ReDoS.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/Complexity.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/OrderedNFA.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/data/Graph.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/DynamicSeeder.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FString.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzChecker.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/StaticSeeder.scala
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/util/RepeatUtil.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/ReDoSSuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/automaton/ComplexitySuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/DynamicSeederSuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/FStringSuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/FuzzCheckerSuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/StaticSeederSuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/util/RepeatUtilSuite.scala
packages/recheck/README.md
packages/recheck/index.d.ts

- Add `StaticSeeder` and set it as the default
- Decrease `incubationLimit`, `maxGeneString` and `maxGeneStringSize` values
- Improve repetition count estimation

Add `StaticSeeder` for the new default seeder

---

CHANGELOG.md
modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/AgentCommandSuite.scala

- Fix semaphore usage in `AgentCommand` test
I believe this fixes the flaky test.

Fix semaphore usage in test

---

CHANGELOG.md
build.sbt

- To disable `lintUnused` false-positive warning, set `excludeLintKeys`.
- Add `better-monadic-for` plugin to `root` for `mdoc` task

Fix sbt file issues

---

CHANGELOG.md
modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/StaticSeeder.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/StaticSeederSuite.scala

- Fix loop detection in StaticSeeder

Fix loop detection in StaticSeeder

---

lerna.json
package.json
yarn.lock

- Use `lerna` to update version
Now we can use `lerna version x.x.x` for updating a version of `recheck` all packages in NPM.

Use lerna to update version

---

CHANGELOG.md
packages/recheck/src/lib/exe.ts

Currently, `java` and `native` backends do not work correctly because `module.require` has no `resolve` method. So, they are errored and fall back unfortunately into `pure`.
- Use require directly instead of module.require

Use require directly instead of module.require

---

CHANGELOG.md
packages/recheck/package.json
packages/recheck/src/lib/__test__/test-agent.js
packages/recheck/src/lib/agent.test.ts
packages/recheck/src/lib/agent.ts

When the `agent` process sends data across two or more `'data'` events, JSON parsing is failed.
This commit fixes `handleLine` in `Agent` to handle such data correctly.
- Fix `handleLine` in `Agent` for large data

Fix `handleLine` in `Agent` for large data

---

.github/workflows/update-changelog.yaml

I wish it fixes a bug.
- Update `CHANGELOG.md` automatically by GitHub Actions

Update `CHANGELOG.md` automatically by GitHub Actions

---

packages/recheck/index.d.ts

- Add missing field `AttackPattern#pattern` in TypeScript definition

Add missing field `AttackPattern#pattern` in TypeScript definition

---

website/babel.config.js

- Fix website babel config for working playground
See:
- <https://stackoverflow.com/questions/42449999/webpack-import-module-exports-in-the-same-module-caused-error>
- <https://github.com/babel/babel/issues/12731#issuecomment-780153966>

Fix website babel config for working playground

---

modules/recheck-core/shared/src/main/scala/codes/quine/labs/recheck/automaton/EpsNFA.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labs/recheck/automaton/AutomatonCheckerSuite.scala
modules/recheck-core/shared/src/test/scala/codes/quine/labs/recheck/automaton/EpsNFASuite.scala

In the past, in `EpsNFA#toOrderedNFA`, next character kinds are omitted after refining a transition, so it equates two states which should be distinguish.
This commit fixes it to include next character kind in state.
Now, we can check `/^.+?aa[^@]@/` correctly.
- Fix zero-width assertion in `automaton` checker

Fix zero-width assertion in `automaton` checker

---

modules/recheck-codec/shared/src/main/scala/codes/quine/labs/recheck/codec/package.scala
modules/recheck-codec/shared/src/test/scala/codes/quine/labs/recheck/codec/CodecSuite.scala

Fix #484
- `get(...).orElse(...)` ignores an error on decoding, it is unexpected. We added to a modified version of `HCursor#getOrElse` and uses it on `Parameter` decoder.
- `Duration` decoder is also rewrited.

Fix `Duration` and `Parameter` decoder for missing keys and `null`

---

website/src/components/Demo.tsx

Fixed #500
- Convert duration params to integer explicitly on the playground. Because HTML `<input>` values are string.

Convert duration params to integer explicitly on playground

---

packages/eslint-plugin-redos/src/configs/recommended.ts
packages/eslint-plugin-redos/src/main.ts
website/docs/usage/as-eslint-plugin.mdx

Fix #691 
- Add `recommended` config to the ESLint plugin
- Update the ESLint plugin document

Add `recommended` config to the ESLint plugin

---

.github/workflows/main.yml

- Use `action-gh-release` for automatically publishing GitHub Release with files.

Use `action-gh-release`

---

LICENSE
README.md
website/docusaurus.config.js

- Update copyright year 2022 -> 2023 in `README.md`, `LICENSE` and `docusaurus.config.js`.

Update copyright year 2022 -> 2023

---

.github/workflows/main.yml
.github/workflows/scala-steward.yml
.github/workflows/update-changelog.yaml

Ref #758
- Pin the version of the CI environments for preventing GLIBC version warning
- `ubuntu-latest` to `ubuntu-20.04`
- `macos-latest` to `macos-12`
- `windows-latest` to `windows-2022`
- See <https://github.com/actions/runner-images>.

Pin the version of the CI environments for preventing GLIBC version warning

---

.github/workflows/main.yml

- Use `$GITHUB_OUTPUT` instead of `set-output`
- See <https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/>

Use `$GITHUB_OUTPUT` instead of `set-output`

---

modules/recheck-cli/src/main/scala/codes/quine/labs/recheck/cli/AgentCommand.scala

- Remove deprecated `System.runFinalizer` call

Remove deprecated `System.runFinalizer` call

---

packages/recheck/src/lib/agent.ts

Ref #758
- Change `stdio` property of the setting on spawning agents from `"ignore"` to `"inherit"`.
- Then, `stderr` output of agent processes will be shown.
- It may prevent issues like #758.

Show `stderr` output of agent processes

---

website/package.json
yarn.lock

- Fix React version to `v17`
* The latest version is `v18`, however Docusaurus `v2` does not support this yet.

Fix React version to v17

---

packages/recheck/src/main.test.ts
packages/recheck/src/main.ts

Close #870
- Fix to work `RECHECK_SYNC_BACKEND` correctly
* A `break` for `switch`-`case` is missing. It is easy mistake.
- Add a test case for checking whether `synckit` function has been called.

Fix to work `RECHECK_SYNC_BACKEND` correctly

---

.github/workflows/main.yml
.scalafix.conf
build.sbt

- Update JVM to use on CI (from v19 to v21)
- Remove some scalafix plugins due to out dated.

Update JVM to use on CI

---

packages/recheck/src/main.ts

This patch fixes an issue where the two functions would never finish if called without a second parameter. For example, check("^(a|a+)+$")

Ensure that checkSync() and check() do not stall without the flags parameter

---

renovate.json

Pin `react-dom` version much like `react` because Docusaurus only supports React v18.

Pin react-dom version
