makenowjust-labs/recheck

.github/workflows/scala.yml, CHANGELOG.md, README.md, build.sbt
And, it enables coverage in ScalaJS build.
=> Send coverage to Codecov

CHANGELOG.md, modules/recheck/js/src/test/scala/codes/quine/labo/recheck/ReDoSJSSuite.scala, modules/recheck/js/src/test/scala/codes/quine/labo/recheck/WrappersSuite.scala, modules/recheck/shared/src/main/scala/codes/quine/labo/recheck/data/UString.scala, modules/recheck/shared/src/test/scala/codes/quine/labo/recheck/fuzz/FuzzCheckerSuite.scala
- Remove unused method `UString#size`
- Add missing tests
=> Improve coverage to 100%

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- Put issue/pull request templates to `.github` directory.
=> Add issue/pull request templates

.github/workflows/release.yml
Fix #150
- Fix `gh-pages` job `if` expression correctly
=> Fix `gh-pages` job `if` expression correctly

.github/workflows/lint.yml, packages/recheck/index.d.ts, packages/recheck/package.json, packages/recheck/src/agent.ts, packages/recheck/src/fallback.ts, packages/recheck/src/index.ts, packages/recheck/tsconfig.json, yarn.lock
Fix #146 
- Introduce `prettier`
- Update workflow to check code format by `prettier`
=> Introduce `prettier`

CHANGELOG.md, packages/recheck/index.d.ts, packages/recheck/src/fallback.ts, packages/recheck/src/index.ts
Fix #153
- Add `checkSync` function to NPM package
=> Add `checkSync`

renovate.json
Fix #158 
- Set `automerge` of Renovate config
=> Set auto-merge for Renovate

.github/workflows/main.yml
Fix #177 
- Use `nick-invision/retry` action for `native-build` job
=> Retry `native-build` job

.github/workflows/main.yml
Fix #179 
- Skip native-build on Pull Request
=> Skip native-build on Pull Request

packages/recheck/src/agent.ts
Fix #157 
- Call `subprocess.ref()`/`unref()` correctly
=> Call `subprocess.ref()`/`unref()` correctly

packages/recheck/package.json
`index.d.ts` is missing in `files` list of `package.json`. This PR adds it.
- Add `index.d.ts` file to the package
=> Add `index.d.ts` file to the package

packages/recheck/package.json, yarn.lock
- Fix `optionalDependencies` in `recheck` package
=> Fix `optionalDependencies` in `recheck` package

packages/eslint-plugin-redos/README.md
- Fix `README.md` in `eslint-plugin-redos`
=> Fix README.md in eslint-plugin-redos

.github/workflows/main.yml
- Update versions of tools using in the workflow
=> Update versions of tools using in the workflow

project/plugin.sbt
- Remove FIXME against `scalajs-env-nodejs`
because this bug is already fixed.
=> Remove FIXME against `scalajs-env-nodejs`

CHANGELOG.md, modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/Main.scala, modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/arguments.scala, modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/ArgumentsSuite.scala, modules/recheck-codec/shared/src/main/scala/codes/quine/labo/recheck/codec/package.scala, modules/recheck-codec/shared/src/test/scala/codes/quine/labo/recheck/codec/CodecSuite.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/AccelerationMode.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Parameters.scala, modules/recheck-common/shared/src/test/scala/codes/quine/labo/recheck/common/AccelerationModeSuite.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/ReDoS.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/Complexity.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzChecker.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzProgram.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/Seeder.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/ReDoSSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/FuzzProgramSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/SeederSuite.scala, packages/recheck/README.md, packages/recheck/index.d.ts
- Add `accelerationMode`
- Rename default parameter constants
- Update default parameter
=> Replace `usesAcceleration` with `accelerationMode`

build.sbt, modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/AgentCommand.scala, modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/Main.scala, modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/RPC.scala, modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/AgentCommandSuite.scala, modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/MainSuite.scala, modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/RPCSuite.scala, modules/recheck-codec/shared/src/main/scala/codes/quine/labo/recheck/codec/package.scala, modules/recheck-codec/shared/src/test/scala/codes/quine/labo/recheck/codec/CodecSuite.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Context.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/ContextMacro.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Parameters.scala, modules/recheck-common/shared/src/test/scala/codes/quine/labo/recheck/common/ContextSuite.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/ReDoS.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/AutomatonChecker.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFA.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFABuilder.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/NFA.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/OrderedNFA.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzChecker.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/vm/Interpreter.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/automaton/OrderedNFASuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/vm/InterpreterSuite.scala, modules/recheck-js/src/main/scala/codes/quine/labo/recheck/ReDoSJS.scala, modules/recheck-js/src/test/scala/codes/quine/labo/recheck/ReDoSJSSuite.scala, packages/recheck/README.md, packages/recheck/index.d.ts, packages/recheck/src/agent.ts, packages/recheck/src/index.ts
=> Support `logger` parameter

.github/workflows/main.yml, packages/eslint-plugin-redos/src/rules/no-vulnerable.test.ts, packages/eslint-plugin-redos/src/rules/no-vulnerable.ts
- Send coverage of `node-test` job
=> Send coverage of node-test

CHANGELOG.md, docs/_index.md, modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/AgentCommandSuite.scala, modules/recheck-codec/shared/src/test/scala/codes/quine/labo/recheck/codec/CodecSuite.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/diagnostics/AttackPattern.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FString.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/diagnostics/AttackPatternSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/diagnostics/DiagnosticsSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/FStringSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/SeederSuite.scala, packages/recheck/README.md
Fix #224 
- Use JavaScript style in `AttackPattern#toString` and `FString#toString`
=> Update `AttackPattern` and `FString` `#toString` style

CHANGELOG.md, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/vm/Interpreter.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/vm/InterpreterSuite.scala
- Check integer overflow on matching steps
=> Check integer overflow on matching steps

build.sbt, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzChecker.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/vm/Inst.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/vm/Interpreter.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/vm/ProgramBuilder.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/vm/InstSuite.scala
- Add look-ahead optimization to VM
=> Add look-ahead optimization to VM

CHANGELOG.md, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/ReDoS.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/AutomatonChecker.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/diagnostics/AttackPattern.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/FuzzChecker.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/diagnostics/AttackPatternSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/FuzzCheckerSuite.scala
- Let `FuzzChecker` return an iterator instead
=> Let FuzzChecker return an iterator instead

LICENSE, README.md, packages/eslint-plugin-redos/LICENSE, packages/eslint-plugin-redos/README.md, packages/recheck/LICENSE, packages/recheck/README.md, site/config.toml
=> Update copyright year

build.sbt
- Set `--initialize-at-build-time` on native-image build
=> Set `--initialize-at-build-time` on native-image build

modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/AgentCommandSuite.scala
=> Fix AgentCommand test

CHANGELOG.md, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/fuzz/StaticSeeder.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/fuzz/StaticSeederSuite.scala
- Improve `StaticSeeding.simplify` against look-around near by repeat
=> Improve `StaticSeeding.simplify` against look-around near by repeat

CHANGELOG.md, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFABuilder.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/regexp/PatternExtensions.scala, modules/recheck-unicode/shared/src/main/scala/codes/quine/labo/recheck/unicode/IChar.scala, modules/recheck-unicode/shared/src/main/scala/codes/quine/labo/recheck/unicode/LRUCache.scala, modules/recheck-unicode/shared/src/test/scala/codes/quine/labo/recheck/unicode/LRUCacheSuite.scala
- Optimize alphabet construction
=> Optimize alphabet construction

CHANGELOG.md, packages/eslint-plugin-redos/package.json, packages/eslint-plugin-redos/scripts/build.ts, packages/recheck/package.json, packages/recheck/scripts/build.ts, yarn.lock
- Don't bundle recheck in eslint-plugin-redos
=> Don't bundle recheck in eslint-plugin-redos

CHANGELOG.md, packages/recheck/src/lib/agent.ts, packages/recheck/src/lib/exe.ts, packages/recheck/src/main.ts
- Prefer to use `native` backend on `RECHECK_BACKEND=auto`
=> Prefer to use `native` backend on `RECHECK_BACKEND=auto`

.github/workflows/main.yml, lerna.json, packages/eslint-plugin-redos/package.json, packages/recheck-jar/package.json, packages/recheck-linux-x64/package.json, packages/recheck-macos-x64/package.json, packages/recheck-windows-x64/package.json, packages/recheck/package.json
=> Use lerna on workflow

.github/workflows/update-changelog.yaml
- Update `CHANGELOG.md` automatically by using GitHub Actions
=> Update `CHANGELOG.md` automatically by using GitHub Actions

.github/workflows/update-changelog.yaml
- Update `CHANGELOG.md` automatically by GitHub Actions
=> Update `CHANGELOG.md` automatically by GitHub Actions

renovate.json
- Update `renovate.json` to update scala deps more
=> Update `renovate.json` to update scala deps more

renovate.json
Fix #276 
- Handle SBT deps by renovate correctly
=> Handle SBT deps by renovate correctly

modules/recheck-cli/src/main/scala/codes/quine/labo/recheck/cli/arguments.scala, modules/recheck-cli/src/test/scala/codes/quine/labo/recheck/cli/ArgumentsSuite.scala, modules/recheck-codec/shared/src/main/scala/codes/quine/labo/recheck/codec/package.scala, modules/recheck-codec/shared/src/test/scala/codes/quine/labo/recheck/codec/CodecSuite.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Checker.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labo/recheck/common/Parameters.scala, modules/recheck-common/shared/src/test/scala/codes/quine/labo/recheck/common/CheckerSuite.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/ReDoS.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/EpsNFA.scala, modules/recheck-core/shared/src/main/scala/codes/quine/labo/recheck/automaton/OrderedNFA.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labo/recheck/ReDoSSuite.scala, packages/eslint-plugin-redos/README.md, packages/eslint-plugin-redos/src/rules/no-vulnerable.ts, packages/recheck/README.md, packages/recheck/index.d.ts, site/assets/js/main.js, site/layouts/partials/header.html
=> Rename `hybrid` to `auto`

.github/workflows/update-changelog.yaml, CHANGELOG.md
- Update `CHANGELOG.md` format
=> Update `CHANGELOG.md` format

packages/eslint-plugin-redos/jest.config.js, packages/eslint-plugin-redos/package.json, packages/eslint-plugin-redos/scripts/build.ts, packages/recheck/index.js, packages/recheck/jest.config.js, packages/recheck/package.json, packages/recheck/scripts/build.ts, packages/recheck/src/browser.ts, packages/recheck/src/inject/main.ts, packages/recheck/src/inject/worker-browser.ts, packages/recheck/src/inject/worker-node.ts, packages/recheck/src/lib/__test__/test-worker-script.js, packages/recheck/src/lib/__test__/test-worker.js, packages/recheck/src/lib/agent.ts, packages/recheck/src/lib/env.ts, packages/recheck/src/lib/worker-pool.test.ts, packages/recheck/src/lib/worker-pool.ts, packages/recheck/src/lib/worker.ts, packages/recheck/src/main.test.ts, packages/recheck/src/main.ts
- Add `worker` backend to the NPM package
=> Add `worker` backend to the NPM package

.github/workflows/main.yml
- Restrict CI timing
- Introduce Reviewdog
=> Restrict CI timing

.github/workflows/main.yml
- Fix workflow to publish `gh-pages` correctly
=> Fix workflow to publish `gh-pages` correctly

website/package.json, yarn.lock
Reverts MakeNowJust-Labo/recheck#308
=> Revert "Update remark monorepo (major)"

renovate.json
- Ignores remark deps from Renovate update
See <https://docusaurus.io/docs/markdown-features/math-equations#configuration>.
=> Ignores remark deps from Renovate update

.github/workflows/main.yml
- Don't ignore to build website on CI test
=> Don't ignore to build website on CI test

website/blog/authors.yml, website/docusaurus.config.js, website/src/pages/index.module.css, website/src/pages/index.tsx
=> Fix logo style

website/docs/usage/as-javascript-library.mdx
- Update docs about worker backend
=> Update docs about worker backend

website/src/pages/index.tsx
=> Fix top page button color

.github/workflows/main.yml, packages/recheck/src/main.test.ts
- Increase timeout on `main.ts` test
- Remove `retry` action
=> Increase timeout on `main.ts` test

website/docusaurus.config.js
=> Enable Algolia DocSearch

modules/recheck-cli/src/main/scala/codes/quine/labs/recheck/cli/Main.scala, modules/recheck-codec/shared/src/main/scala/codes/quine/labs/recheck/codec/package.scala, modules/recheck-common/shared/src/main/scala/codes/quine/labs/recheck/common/Parameters.scala, packages/recheck/index.d.ts, website/docs/usage/parameters.md, website/src/components/Demo.tsx
- Sort `Parameters` names in lexicographic order
=> Sort `Parameters` names in lexicographic order

website/src/components/Demo.module.css, website/src/components/Demo.tsx
=> Enable log on playground

.github/workflows/main.yml
=> Fix Windows build

website/src/components/Demo.tsx
=> Fix log scroll

lerna.json, package.json, packages/eslint-plugin-redos/package.json, packages/recheck-jar/package.json, packages/recheck-linux-x64/package.json, packages/recheck-macos-x64/package.json, packages/recheck-windows-x64/package.json, packages/recheck/package.json, website/package.json
By using https://devina.io/package-json-formatter
- Format `package.json` by using https://devina.io/package-json-formatter
=> Format `package.json` by using https://devina.io/package-json-formatter

modules/recheck-core/shared/src/main/scala/codes/quine/labs/recheck/vm/Interpreter.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labs/recheck/fuzz/FuzzCheckerSuite.scala, modules/recheck-core/shared/src/test/scala/codes/quine/labs/recheck/vm/InterpreterSuite.scala
- Correct to increase steps on back-reference
=> Correct to increase steps on back-reference

.github/workflows/main.yml
- Update Node.js to v18 for a new Jest
=> Update Node.js to v18

.github/workflows/main.yml, README.md
- Update workflow
- Fix badge URL in README.md
=> Update workflow for using coursier/setup-action

build.sbt
- Update GraalVM version to 22.3.0
=> Update GraalVM version

.github/workflows/main.yml
- Correctly set version to `$GITHUB_OUTPUT`
=> Correctly set version to `$GITHUB_OUTPUT`

.github/workflows/main.yml
- Rename artifact files before release
=> Rename artifact files before release

modules/recheck-exec/js/src/main/scala/codes/quine/labs/recheck/exec/NodeExecutor.scala
- Remove useless `@nowarn` annotation
=> Remove useless `@nowarn` annotation

website/blog/2022-02-04-release-v4.3.0.md, website/blog/2022-05-17-release-v4.4.0.md
- Fix heading in blog articles
=> Fix heading in blog articles

packages/eslint-plugin-redos/jest.config.js, packages/eslint-plugin-redos/package.json, packages/eslint-plugin-redos/src/rules/no-vulnerable.ts, packages/eslint-plugin-redos/src/utils/cache.ts, packages/eslint-plugin-redos/src/utils/checker.test.ts, packages/eslint-plugin-redos/src/utils/checker.ts, packages/eslint-plugin-redos/src/utils/version.ts, website/docs/usage/as-eslint-plugin.mdx, yarn.lock
- Add `cache` option to `eslint-plugin-redos`.
- Update docs.
=> Add `cache` option to `eslint-plugin-redos`

packages/eslint-plugin-redos/package.json, packages/eslint-plugin-redos/src/rules/no-vulnerable.ts, packages/eslint-plugin-redos/src/utils/cache.ts, packages/eslint-plugin-redos/src/utils/checker.ts, packages/eslint-plugin-redos/src/utils/version.ts, yarn.lock
=> Fix up cache implementation

packages/eslint-plugin-redos/src/utils/checker.test.ts, packages/eslint-plugin-redos/src/utils/checker.ts, website/docs/usage/as-eslint-plugin.mdx
Close #784
- Set `'conservative'` as default `cache.strategy`
=> Set `'conservative'` as default `cache.strategy`

.github/workflows/main.yml, build.sbt
- Set `dist-tag` for NPM publish
- Set `versionScheme` of `build.sbt`
=> Improve publish settings

.github/workflows/main.yml
Reverts makenowjust-labs/recheck#1036
=> Revert "Update codecov/codecov-action action to v4"

modules/recheck-core/shared/src/main/scala/codes/quine/labs/recheck/diagnostics/AttackPattern.scala, modules/recheck-unicode/shared/src/main/scala/codes/quine/labs/recheck/unicode/Property.scala, packages/eslint-plugin-redos/src/rules/no-vulnerable.test.ts, packages/eslint-plugin-redos/src/rules/no-vulnerable.ts, packages/recheck/src/lib/worker-pool.ts, website/docs/usage/as-eslint-plugin.mdx
=> Fix some typos

LICENSE, README.md, website/docusaurus.config.js
- Update copyright year 2023 -> 2024
=> Update copyright year 2023 -> 2024

.github/workflows/main.yml, packages/recheck/package.json
- This drops Node.js v16 support.
=> Update supported Node.js version

.github/workflows/main.yml, packages/recheck-macos-arm64/README.md, packages/recheck-macos-arm64/package.json, packages/recheck/src/lib/exe.ts
Fix #956
- Add `recheck-macos-arm64`
=> Add `recheck-macos-arm64`

.github/workflows/main.yml
- Install sbt explicitlly on CI
=> Install sbt explicitlly on CI

website/docusaurus.config.js
- Enable Google Analytics for website
=> Enable Google Analytics for website

.github/workflows/main.yml
=> Specify CODECOV_TOKEN

packages/recheck/package.json
- Add `recheck-macos-arm64` to `recheck`'s `optionalDeps`
=> Add `recheck-macos-arm64` to `recheck`'s `optionalDeps`

packages/recheck/src/lib/env.test.ts, packages/recheck/src/lib/env.ts
- Add a test for `RECHECK_SYNC_BACKEND` env
=> Add a test for `RECHECK_SYNC_BACKEND` env

packages/eslint-plugin-redos/src/utils/cache.test.ts, packages/eslint-plugin-redos/src/utils/cache.ts, packages/eslint-plugin-redos/src/utils/checker.test.ts, packages/eslint-plugin-redos/src/utils/checker.ts
=> Add a test for caches

.github/workflows/main.yml
- Add `timeout-minutes` to workflow
=> Add `timeout-minutes` to workflow

packages/eslint-plugin-redos/package.json, packages/recheck/package.json, website/docs/internals/background.mdx, website/docs/internals/fuzzing.mdx, website/docs/internals/matching-acceleration.mdx, website/docs/intro.mdx, website/package.json, yarn.lock
Close #1265
Close #1388 
- Update Prettier to v3.5.2
- Update ESBuild to v0.25.0
=> Update JS deps

packages/eslint-plugin-redos/package.json, packages/eslint-plugin-redos/src/rules/no-vulnerable.test.ts, yarn.lock
=> Use ESLint v9

LICENSE, README.md, website/docusaurus.config.js
Update copyright year from 2024 to 2025.
=> Update copyright year 2024 -> 2025

.github/workflows/main.yml, packages/eslint-plugin-redos/package.json, packages/recheck/package.json
Drop Node v18 support since its support will be terminated in 2025-04.
=> Drop Node v18 support
